### ISSUE TITLE
Unable to initialise iSquash Controller

### ISSUE THREAD

**Issue by NathanDunning** [madduck/pytcnz#1]
**Describe the bug**
When the iSquash Controller attempts to initialise, it throws a `TypeError` with the following stack and message:
```
File "C:\venv\pytcnz\squashnz\isquash_controller.py line 95, in __init__
    self.driver = iSquashController.__get_firefox_driver(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\venv\pytcnz\squashnz\isquash_controller.py  line 85, in __get_firefox_driver
    return webdriver.Firefox(
               ^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'
```

**To Reproduce**
1. Running the tc-tools script to attempt to update results, execute `python enter_isquash_results.py -u $USER -p $PW -t $CODE -i .\tc-export.ods`

**Expected behavior**
Firefox Webdriver to initiate successfully

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 87.0 (64-bit)

**Comment by madduck** [comment]
My first bug report!! ;)

Can confirm. WebDriver seems to have changed the API. Will have a fix shortly.

**Comment by NathanDunning** [comment]
Raised a PR which fixes it for me, haven't looked too much into how I can supply the deprecated options of Profile and Log Path.
